# Configuration for the mover script
Paths:
  CACHE_PATH: /mnt/cache-disks/cache01
  BACKING_PATH: /mnt/media-cold
  LOG_PATH: /var/log/cache-mover.log

Settings:
  THRESHOLD_PERCENTAGE: 10
  USER: media
  GROUP: media
  CHMOD: 770
  MAX_WORKERS: 8
  MAX_LOG_SIZE_MB: 100
  BACKUP_COUNT: 5